
---
apiVersion: v1
kind: Secret
metadata:
  name: consultaplanfs-js-proxy
  annotations:
    maven.jkube.io/secret/application.properties: ${project.basedir}/src/main/resources/application.properties
   